version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: products
      host: postgres
      POSTGRES_DB: product_detail
      POSTGRES_PASSWORD: '@Sql5432'
    ports:
      - '5436:5432'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
