version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: products
      host: postgres
      POSTGRES_DB: product_detail
      POSTGRES_PASSWORD: '@Sql5432'
    ports:
      - '5436:5432'
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
